version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: spring_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/project
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_FLYWAY_URL=jdbc:postgresql://db:5432/project
      - SPRING_FLYWAY_USER=admin
      - SPRING_FLYWAY_PASSWORD=admin


volumes:
  postgres_data:
