spring.datasource.url=jdbc:postgresql://localhost:5432/project
spring.datasource.username=admin
spring.datasource.password=admin
spring.flyway.locations=classpath:db/migration,classpath:db/mockdata

fcm.credentials.path=firebase-credentials.json
