spring.application.name=blokur

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JPA - Flyway zarzadza schematem, Hibernate nie powinien modyfikowac
spring.jpa.hibernate.ddl-auto=none
